[package]
name = "pyrin-contracts-runtime"
description = "Pyrin Smart Contracts - Runtime Environment"
rust-version.workspace = true
version.workspace = true
edition.workspace = true
authors.workspace = true
include.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
pyrin-contracts-core = { version = "0.14.1", path = "../core" }
pyrin-contracts-storage = { version = "0.14.1", path = "../storage" }
pyrin-contracts-vm = { version = "0.14.1", path = "../vm" }
pyrin-hashes = { workspace = true }
pyrin-consensus-core = { workspace = true }

borsh = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
parking_lot = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }

[features]
default = []
